// lib/models/practice_attempt.dart

class PracticeAttempt {
  final int? id; // Will be auto-generated by the database
  final String userId; // For future-proofing, e.g., "local_user_01"
  final String questionId; // From your JSON, e.g., "center_of_mass_qn_001"
  final bool wasCorrect; // The result of the user's answer
  final String topic; // From your JSON tags.chapter, e.g., "Center_of_Mass"
  final DateTime timestamp; // The time the attempt was made

  PracticeAttempt({
    this.id,
    required this.userId,
    required this.questionId,
    required this.wasCorrect,
    required this.topic,
    required this.timestamp,
  });

  // Helper method to convert the object to a Map for database insertion.
  Map<String, dynamic> toMap() {
    return {
      'id': id,
      'userId': userId,
      'questionId': questionId,
      'wasCorrect': wasCorrect ? 1 : 0, // Convert bool to integer
      'topic': topic,
      'timestamp': timestamp.millisecondsSinceEpoch, // Convert DateTime to integer
    };
  }
}